{
 "title": "Overmind",
 "tags": [ "screeps" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {}
   },
   {
    "name": "shard",
    "label": "Shard",
    "query": {}
   },
   {
    "name": "user",
    "label": "User",
    "query": {}
   },
   {
    "name": "colonies",
    "label": "Colonies",
    "query": {}
   },
   {
    "name": "resources",
    "label": "Resources",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "CPU / Bucket / Resets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(data.$server.$shard.$user.cpu.getUsed, 'CPU')"
    },
    {
     "target": "alias(data.$server.$shard.$user.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(movingAverage(data.$server.$shard.$user.cpu.getUsed, '1hour'), 'Average CPU')"
    },
    {
     "target": "alias(data.$server.$shard.$user.cpu.limit, 'Limit')"
    },
    {
     "target": "alias(changed(data.$server.$shard.$user.persistent.lastGlobalReset), 'Global Reset')"
    },
    {
     "target": "alias(changed(data.$server.$shard.$user.persistent.lastMemoryReset), 'Memory Reset')"
    },
    {
     "target": "alias(data.$server.$shard.$user.persistent.avgCPU, 'avgCPU')"
    },
    {
     "target": "alias(data.$server.$shard.$user.persistent.isProfiling, 'profiling')"
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "data.$server.$shard.$user.cpu.bucket"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B / $C * 100", "type": "math" }
   ]
  },
  {
   "title": "Empire Age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "IVM Heap Statistics",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(exclude(keepLastValue(data.$server.$shard.$user.cpu.heapStatistics.*, 500), 'does_zap_garbage'), 7)"
    }
   ]
  },
  {
   "title": "Build #",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "data.$server.$shard.$user.persistent.build"
    }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "Expansion Ranking",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "data.$server.$shard.$user.leaderboard.rank"
    }
   ]
  },
  {
   "title": "GCL Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(scaleToSeconds(movingAverage(perSecond(keepLastValue(data.$server.$shard.$user.gcl.progress, 100)), 10), 86400), 'GCL / 24hr')"
    },
    {
     "target": "alias(diffSeries(data.$server.$shard.$user.gcl.progressTotal, data.$server.$shard.$user.gcl.progress), 'Remaining until next level')"
    },
    {
     "target": "alias(scaleToSeconds(movingAverage(perSecond(keepLastValue(data.$server.$shard.$user.gcl.progress, 100)), '1day'), 86400), 'GCL / 24hr (avg)')"
    }
   ]
  },
  {
   "title": "GCL by Colony",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(scale(movingAverage(perSecond(keepLastValue(data.$server.$shard.$user.colonies.$colonies.rcl.progress, 100)), '1min'), 86400)), 6)"
    }
   ]
  },
  {
   "title": "Time to next GCL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "divideSeries(#B, #A)",
     "targetFull": "divideSeries(alias(keepLastValue(diffSeries(data.$server.$shard.$user.gcl.progressTotal, data.$server.$shard.$user.gcl.progress)), 'Progress to go'), alias(scale(movingAverage(perSecond(keepLastValue(data.$server.$shard.$user.gcl.progress)), '1day'), 86400), 'GCL / 24hr (avg)'))"
    }
   ]
  },
  {
   "title": "GPL Progress",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "Power Ranking",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "data.$server.$shard.$user.leaderboard.rank"
    }
   ]
  },
  {
   "title": "GPL Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(scaleToSeconds(movingAverage(perSecond(keepLastValue(data.$server.$shard.$user.gpl.progress, 100)), 10), 86400), 'GPL / 24hr')"
    },
    {
     "target": "alias(diffSeries(data.$server.$shard.$user.gpl.progressTotal, data.$server.$shard.$user.gpl.progress), 'Remaining until next level')"
    },
    {
     "target": "alias(scaleToSeconds(movingAverage(perSecond(keepLastValue(data.$server.$shard.$user.gpl.progress, 100)), '1day'), 86400), 'GPL / 24hr (avg)')"
    }
   ]
  },
  {
   "title": "GPL by Colony",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(scale(movingAverage(perSecond(keepLastValue(data.$server.$shard.$user.colonies.$colonies.rpl.progress, 100)), '1min'), 86400)), 6)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "aliasByNode(data.$server.$shard.$user.cpu.usage.*.*, 7, 8)"
    }
   ]
  },
  {
   "title": "Colonies Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "rooms",
   "targets": [
    {}
   ]
  },
  {
   "title": "DEFCON Levels",
   "type": "bargauge",
   "gridPos": { "h": 28, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(data.$server.$shard.$user.colonies.*.defcon), 6)"
    }
   ]
  },
  {
   "title": "Hatchery Uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(movingAverage(keepLastValue(data.$server.$shard.$user.colonies.$colonies.hatchery.uptime), '1hour'), 6), '(.*)', '\\1 — Uptime')"
    },
    {
     "target": "aliasSub(aliasByNode(movingAverage(keepLastValue(data.$server.$shard.$user.colonies.$colonies.hatchery.overload), '1hour'), 6), '(.*)', '\\1 — Overload')"
    }
   ]
  },
  {
   "title": "Average Barrier Hits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(keepLastValue(data.$server.$shard.$user.colonies.*.avgBarrierHits, 100), 6), '(.*)', '$1 — Average')"
    },
    {
     "target": "aliasSub(aliasByNode(keepLastValue(data.$server.$shard.$user.colonies.*.maxBarrierHits, 100), 6), '(.*)', '$1 — Wanted')"
    }
   ]
  },
  {
   "title": "Energy Assets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(data.$server.$shard.$user.colonies.$colonies.assets.energy, 100), 6)"
    }
   ]
  },
  {
   "title": "Lab uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(keepLastValue(data.$server.$shard.$user.colonies.$colonies.evolutionChamber.avgUsage, 500), '1hour'), 6)"
    }
   ]
  },
  {
   "title": "RCL Progress Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(keepLastValue(data.$server.$shard.$user.colonies.$colonies.rcl.progress, 100), 6), '(.*)', '\\1 — Progress')"
    },
    {
     "target": "aliasSub(aliasByNode(keepLastValue(data.$server.$shard.$user.colonies.$colonies.rcl.progressTotal, 100), 6), '(.*)', '\\1 — Total')"
    },
    {
     "target": "aliasSub(aliasByNode(derivative(data.$server.$shard.$user.colonies.$colonies.rcl.progress), 6), '(.*)', '\\1 — Rate')"
    }
   ]
  },
  {
   "title": "Factory uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(keepLastValue(data.$server.$shard.$user.colonies.$colonies.infestedFactory.avgUsage, 500), '1hour'), 6)"
    }
   ]
  },
  {
   "title": "Average Mining Site Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(movingAverage(keepLastValue(data.$server.$shard.$user.colonies.$colonies.miningSites.avgUsage, 100), '30min'), 6), '(.*)', 'Usage - \\1')"
    },
    {
     "target": "aliasSub(aliasByNode(keepLastValue(data.$server.$shard.$user.colonies.$colonies.miningSites.avgDowntime, 100), 6), '(.*)', 'Downtime - \\1')"
    }
   ]
  },
  {
   "title": "Energy Income Per Tick",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(keepLastValue(data.$server.$shard.$user.colonies.$colonies.miningSites.energyInPerTick, 500), '30min'), 6)"
    },
    {
     "target": "aliasSub(aliasByNode(movingAverage(keepLastValue(data.$server.$shard.$user.colonies.$colonies.miningSites.energyInPerTick, 500), '1d'), 6), '(.*)', '\\1 - Average')"
    }
   ]
  },
  {
   "title": "Creep Population",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 63 },
   "targets": [
    {
     "target": "alias(sum(data.$server.$shard.$user.colonies.*.creeps.*.current), 'Total')"
    },
    {
     "target": "alias(sum(data.$server.$shard.$user.colonies.*.creeps.*.needed), 'Needed')"
    }
   ]
  },
  { "title": "Colony $colonies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }, "repeat": "colonies" },
  {
   "title": "Energy Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(absolute(data.$server.$shard.$user.colonies.$colonies.energyUsage.*), 6, 8), '(.*)\\.(.*)', '\\2')"
    }
   ]
  },
  {
   "title": "Creep Population",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 70 },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(data.$server.$shard.$user.colonies.$colonies.creeps.*.current, 6, 8), '(.*)\\.(.*)', '\\2 (Current)')"
    },
    {
     "target": "aliasSub(aliasByTags(removeAbovePercentile(data.$server.$shard.$user.colonies.$colonies.creeps.*.needed, 99), 6, 8), '(.*)\\.(.*)', '\\2 (Needed)')"
    }
   ]
  },
  {
   "title": "Energy Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sum(absolute(data.$server.$shard.$user.colonies.$colonies.energyUsage.*)), 'total', false)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "target": "aliasByNode(data.$server.$shard.$user.cpu.usage.$colonies.*, 7, 8)"
    }
   ]
  },
  {
   "title": "Terminal Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "keepLastValue(sumSeries(data.$server.$shard.$user.persistent.terminalNetwork.assets.energy))"
    }
   ]
  },
  {
   "title": "Global Assets",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 21, "x": 3, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "exclude(aliasByNode(#A, 0), '^(energy|power)$')",
     "targetFull": "exclude(aliasByNode(groupByNodes(removeBelowValue(removeZeroSeries(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500)), 0), 'sum', 8), 0), '^(energy|power)$')"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "keepLastValue(sumSeries(data.$server.$shard.$user.persistent.terminalNetwork.assets.power))"
    }
   ]
  },
  {
   "title": "Energy Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(data.$server.$shard.$user.persistent.terminalNetwork.incomingResources.energy.*))), 86400), '1day'), 'Incoming', false)"
    },
    {
     "target": "alias(movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(data.$server.$shard.$user.persistent.terminalNetwork.outgoingResources.energy.*))), 86400), '1day'), 'Outgoing', false)"
    }
   ]
  },
  {
   "title": "Fractional Energy Transfer Cost",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "refCount": -1,
     "target": "keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.fractionalEnergyTransferCost)"
    }
   ]
  },
  {
   "title": "Transaction Costs per 24h",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "refCount": -1,
     "target": "alias(movingAverage(scaleToSeconds(perSecond(sumSeries(data.$server.$shard.$user.persistent.terminalNetwork.sendCosts.*)), 86400), '1hour'), 'Cost/24h', false)"
    }
   ]
  },
  {
   "title": "T0 Assets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(grep(#A, '^(H|O|U|K|L|Z|X|OH|ZK|UL|G)$'), 0)",
     "targetFull": "aliasByNode(grep(groupByNodes(removeBelowValue(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500), 0), 'sum', 8), '^(H|O|U|K|L|Z|X|OH|ZK|UL|G)$'), 0)"
    }
   ]
  },
  {
   "title": "T0 Resource Production/Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(derivative(grep(#A, '^(|H|O|U|K|L|Z|X)$')), '1hour'), 0)",
     "targetFull": "aliasByNode(movingAverage(derivative(grep(groupByNodes(removeBelowValue(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500), 0), 'sum', 8), '^(|H|O|U|K|L|Z|X)$')), '1hour'), 0)"
    }
   ]
  },
  {
   "title": "T1 Assets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(grep(#A, '^(UH|UO|KH|KO|LH|LO|ZH|ZO|GH|GO)$'), 0)",
     "targetFull": "aliasByNode(grep(groupByNodes(removeBelowValue(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500), 0), 'sum', 8), '^(UH|UO|KH|KO|LH|LO|ZH|ZO|GH|GO)$'), 0)"
    }
   ]
  },
  {
   "title": "T1 Resource Production/Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(derivative(grep(#A, '^(UH|UO|KH|KO|LH|LO|ZH|ZO|GH|GO)$')), '1hour'), 0)",
     "targetFull": "aliasByNode(movingAverage(derivative(grep(groupByNodes(removeBelowValue(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500), 0), 'sum', 8), '^(UH|UO|KH|KO|LH|LO|ZH|ZO|GH|GO)$')), '1hour'), 0)"
    }
   ]
  },
  {
   "title": "T2 Assets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(grep(#A, '^(UH2O|UHO2|KH2O|KHO2|LH2O|LHO2|ZH2O|ZHO2|GH2O|GHO2)$'), 0)",
     "targetFull": "aliasByNode(grep(groupByNodes(removeBelowValue(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500), 0), 'sum', 8), '^(UH2O|UHO2|KH2O|KHO2|LH2O|LHO2|ZH2O|ZHO2|GH2O|GHO2)$'), 0)"
    }
   ]
  },
  {
   "title": "T2 Resource Production/Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(derivative(grep(#A, '^(UH2O|UHO2|KH2O|KHO2|LH2O|LHO2|ZH2O|ZHO2|GH2O|GHO2)$')), '1hour'), 0)",
     "targetFull": "aliasByNode(movingAverage(derivative(grep(groupByNodes(removeBelowValue(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500), 0), 'sum', 8), '^(UH2O|UHO2|KH2O|KHO2|LH2O|LHO2|ZH2O|ZHO2|GH2O|GHO2)$')), '1hour'), 0)"
    }
   ]
  },
  {
   "title": "T3 Assets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(grep(#A, '^(XUH2O|XUHO2|XKH2O|XKHO2|XLH2O|XLHO2|XZH2O|XZHO2|XGH2O|XGHO2)$'), 0)",
     "targetFull": "aliasByNode(grep(groupByNodes(removeBelowValue(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500), 0), 'sum', 8), '^(XUH2O|XUHO2|XKH2O|XKHO2|XLH2O|XLHO2|XZH2O|XZHO2|XGH2O|XGHO2)$'), 0)"
    }
   ]
  },
  {
   "title": "T3 Resource Production/Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(derivative(grep(#A, '^(XUH2O|XUHO2|XKH2O|XKHO2|XLH2O|XLHO2|XZH2O|XZHO2|XGH2O|XGHO2)$')), '1hour'), 0)",
     "targetFull": "aliasByNode(movingAverage(derivative(grep(groupByNodes(removeBelowValue(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500), 0), 'sum', 8), '^(XUH2O|XUHO2|XKH2O|XKHO2|XLH2O|XLHO2|XZH2O|XZHO2|XGH2O|XGHO2)$')), '1hour'), 0)"
    }
   ]
  },
  {
   "title": "Commodities",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(grep(#A, '^(utrium_bar|lemergium_bar|zynthium_bar|keanium_bar|ghodium_melt|oxidant|reductant|purifier|battery|metal|alloy|tube|fixtures|frame|hydraulics|machine|biomass|cell|phlegm|tissue|muscle|organoid|organism|silicon|wire|switch|transistor|microchip|circuit|device|mist|condensate|concentrate|extract|spirit|emanation|essence)$'), 0)",
     "targetFull": "aliasByNode(grep(groupByNodes(removeBelowValue(removeZeroSeries(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500)), 0), 'sum', 8), '^(utrium_bar|lemergium_bar|zynthium_bar|keanium_bar|ghodium_melt|oxidant|reductant|purifier|battery|metal|alloy|tube|fixtures|frame|hydraulics|machine|biomass|cell|phlegm|tissue|muscle|organoid|organism|silicon|wire|switch|transistor|microchip|circuit|device|mist|condensate|concentrate|extract|spirit|emanation|essence)$'), 0)"
    }
   ]
  },
  {
   "title": "Commodities Production/Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(derivative(grep(#A, '^(utrium_bar|lemergium_bar|zynthium_bar|keanium_bar|ghodium_melt|oxidant|reductant|purifier|battery|metal|alloy|tube|fixtures|frame|hydraulics|machine|biomass|cell|phlegm|tissue|muscle|organoid|organism|silicon|wire|switch|transistor|microchip|circuit|device|mist|condensate|concentrate|extract|spirit|emanation|essence)$')), '1hour'), 0)",
     "targetFull": "aliasByNode(movingAverage(derivative(grep(groupByNodes(removeZeroSeries(removeBelowValue(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500), 0)), 'sum', 8), '^(utrium_bar|lemergium_bar|zynthium_bar|keanium_bar|ghodium_melt|oxidant|reductant|purifier|battery|metal|alloy|tube|fixtures|frame|hydraulics|machine|biomass|cell|phlegm|tissue|muscle|organoid|organism|silicon|wire|switch|transistor|microchip|circuit|device|mist|condensate|concentrate|extract|spirit|emanation|essence)$')), '1hour'), 0)"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(grep(#A, '^(power|ops)$'), 0)",
     "targetFull": "aliasByNode(grep(groupByNodes(removeBelowValue(removeZeroSeries(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500)), 0), 'sum', 8), '^(power|ops)$'), 0)"
    }
   ]
  },
  {
   "title": "Power Production/Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(derivative(grep(#A, '^(power|ops)$')), '1hour'), 0)",
     "targetFull": "aliasByNode(movingAverage(derivative(grep(groupByNodes(removeZeroSeries(removeBelowValue(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.assets.$resources, 500), 0)), 'sum', 8), '^(power|ops)$')), '1hour'), 0)"
    }
   ]
  },
  {
   "title": "Incoming Energy Rate",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 226 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(movingAverage(scaleToSeconds(perSecond(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.incomingResources.energy.*)), 86000), '24hour')), 9)"
    }
   ]
  },
  {
   "title": "Incoming Energy per 24h",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(movingAverage(perSecond(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.incomingResources.energy.*)), '4hour'), 86000), 9)"
    }
   ]
  },
  {
   "title": "Outgoing Energy Rate",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 233 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(movingAverage(scaleToSeconds(perSecond(keepLastValue(data.$server.$shard.$user.persistent.terminalNetwork.outgoingResources.energy.*)), 86000), '24hour')), 9)"
    }
   ]
  },
  {
   "title": "Outgoing Energy per 24h",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(data.$server.$shard.$user.persistent.terminalNetwork.outgoingResources.energy.*, 9, 'sumSeries'))), '4hour'), 86000), 0)"
    }
   ]
  },
  {
   "title": "Trade Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 240 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Credits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "data.$server.$shard.$user.persistent.trader.credits"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(keepLastValue(data.$server.$shard.$user.persistent.trader.credits), 'Credits')"
    }
   ]
  },
  {
   "title": "ΔCredits / 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 245 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(scaleToSeconds(derivative(keepLastValue(data.$server.$shard.$user.persistent.trader.credits, 500)), 86400), '∆Credits/24h', false)"
    }
   ]
  },
  {
   "title": "Resource Transactions per 24h (Amounts)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(scaleToSeconds(perSecond(movingAverage(keepLastValue(data.$server.$shard.$user.persistent.trader.bought.$resources.amount), 100)), 86000)), 8)"
    },
    {
     "target": "aliasByNode(removeZeroSeries(scaleToSeconds(perSecond(movingAverage(keepLastValue(data.$server.$shard.$user.persistent.trader.sold.$resources.amount), 100)), -86000)), 8)"
    }
   ]
  },
  {
   "title": "Market Prices",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 16, "x": 8, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(data.$server.$shard.$user.persistent.trader.prices.$resources.avg, 10), 8)"
    }
   ]
  },
  {
   "title": "Resource Transactions per 24h (Credits)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 259 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(scaleToSeconds(perSecond(movingAverage(keepLastValue(data.$server.$shard.$user.persistent.trader.bought.$resources.credits), 100)), -86000)), 8)"
    },
    {
     "target": "aliasByNode(removeZeroSeries(scaleToSeconds(perSecond(movingAverage(keepLastValue(data.$server.$shard.$user.persistent.trader.sold.$resources.credits), 100)), 86000)), 8)"
    }
   ]
  }
 ]
}