name: Deploy to Main

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: grunt

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Enable caching for npm dependencies

    - name: Install Dependencies
      run: npm ci
    - name: Build
      env:
        SCREEPS_EMAIL: ${{ vars.EMAIL }}
        SCREEPS_TOKEN: ${{ secrets.SCREEPSTOKEN }}
        SCREEPS_BRANCH: ${{ vars.BRANCH || 'default' }}
        SCREEPS_PTR: ${{ vars.PTR || 'false' }}
      run: |
        grunt --email="$SCREEPS_EMAIL" --token="$SCREEPS_TOKEN" --branch="$SCREEPS_BRANCH" --ptr="$SCREEPS_PTR"
