name: Deploy to PTR

on:
  push:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Screeps branch to deploy to'
        required: false
        default: 'default'
        type: string

jobs:
  ptr:
    runs-on: ubuntu-latest
    environment: grunt
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Deploy to PTR
      env:
        SCREEPS_EMAIL: ${{ vars.EMAIL }}
        SCREEPS_TOKEN: ${{ secrets.SCREEPSTOKEN }}
        SCREEPS_BRANCH: ${{ inputs.branch_name || vars.BRANCH || 'default' }}
      run: |
        npm install
        grunt --email="$SCREEPS_EMAIL" --token="$SCREEPS_TOKEN" --branch="$SCREEPS_BRANCH" --ptr=true
